# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:13.8.0
  working_directory: ~/job

commands:
  print_pipeline_id:
    description: "an example of command on circle ci"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

# Orchestrate or schedule a set of jobs
jobs:

  save_hello_world_output:
    <<: *defaults
    steps:
      - run: echo "hello world" > output.txt
      - print_pipeline_id
      - persist_to_workspace:
          root: ~/job/
          paths:
            - output.txt

  print_output_file:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/job
      - run: cat ~/job/output.txt

  job_to_fail:
    <<: *defaults
    steps:
      - run: return 1
      - run:
          name: on error
          command: echo "previos job failed"
          when: on_fail

workflows:
  # Name the workflow "welcome"
  sharing_files:
    # Run the welcome/run job in its own container
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - job_to_fail
