# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Orchestrate or schedule a set of jobs
jobs:
  defaults: &defaults
    docker:
      - image: circleci/node:13.8.0
    working_directory: ~/job
  save_hello_world_output:
    <<: *defaults
    steps:
      - run: echo "hello world" > output.txt
      - persist_to_workspace:
          root: ~/job/
          paths:
            - output.txt
  print_output_file:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/job
      - run: cat ~/job/output.txt
workflows:
  # Name the workflow "welcome"
  sharing_files:
    # Run the welcome/run job in its own container
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
